evaluator_request:
    Qwen_7B_comment_Tuned_model : "./data/models/LLM_TQ_Tuned_model"
    Regression_model_base : "./data/models/nlp_bert_backbone_base_std"
    Regression_model_regression : "./data/models/LLM_TQ_Regression_model/best_regression_bert_tri_inputs.pth"
    calculate_device : "cpu"

